[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "zyncdb"
path = "src/main.rs"

[dependencies]
zyncdb-core = { path = "../core" }
parser = { path = "../parser" }
log = "0.4"
env_logger = "0.10"

[[bin]]
name = "console"
path = "src/bin/console.rs"